# ----- JPA and Hibernate configuration -----

spring.jpa.open-in-view=false

spring.jpa.hibernate.ddl-auto=update

# Uncomment to print the SQL statements (note that the logs do not integrate with the logging framework)
spring.jpa.show-sql=true

# Uncomment to "pretty print" the SQL logs
#spring.jpa.properties.hibernate.format_sql=true

# Uncomment to prefix the SQL logs with the HQL
#spring.jpa.properties.hibernate.use_sql_comments=true

# Uncomment to log queries slower than a certain duration (but it may not work well with H2 since the embedded DB is too fast)
spring.jpa.properties.hibernate.log_slow_query=1

# Uncomment to enable the statistics
spring.jpa.properties.hibernate.generate_statistics=true

# Uncomment to use a custom Hibernate session metrics logger (that does not require the statistics to be enabled)
spring.jpa.properties.hibernate.session.events.auto=com.adeliosys.sample.CustomSessionEventListener

# ----- Hikari datasource configuration -----

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.register-mbeans=true

# ----- Logging configuration -----

logging.level.com.adeliosys=debug

# Uncomment to log the SQL statements
#logging.level.org.hibernate.SQL=debug

# Uncomment to log the parameters of the SQL statements
#logging.level.org.hibernate.orm.jdbc.bind=trace

# Uncomment to log the statement metrics (this requires the statistics to be enabled)
#logging.level.org.hibernate.statistics=debug

# Uncomment to log the session metrics (this does not require the statistics to be enabled)
#logging.level.org.hibernate.session.metrics=debug
